- id: '1537390101427'
  alias: Mở TV 60 phút
  trigger: []
  condition: []
  action:
  - alias: ''
    data:
      entity_id: switch.tv
    service: switch.turn_on
  - delay: 00:60:00
  - data:
      entity_id: switch.tv
    service: switch.turn_off
- alias: TV Timer
  trigger:
    platform: time
    minutes: /1
    seconds: 0
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: switch.tv
      state: 'off'
    - condition: template
      value_template: '{{ now().time().strftime("%H:%M") == states.sensor.alarm.state
        }}'
  action:
    service: switch.tv
    entity_id: switch.tv
  id: 9f5c634649c0426285a966bfb1c8ca1d
- id: '1541048521506'
  alias: hẹn giờ
  trigger:
  - at: '12:19'
    platform: time
  condition: []
  action:
  - service: switch.turn_on
  - delay: 00:00:30
  - service: switch.turn_off
- id: '1541058987488'
  alias: Mở TV 30 phút
  trigger: []
  condition: []
  action:
  - data:
      entity_id: switch.tv
    service: switch.turn_on
  - delay: 00:30:00
  - data:
      entity_id: switch.tv
    service: switch.turn_off
- id: '1541058987482'
  alias: on...........
  trigger:
  - platform: template
    value_template: '{{ (states.input_datetime.heating_on_weekday.attributes.timestamp
      | int | timestamp_custom("%H:%M", False)) == states.sensor.time.state }}'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id: input_select.heating_scene
      option: Hoch
    service: input_select.select_option
- alias: Porch Animation Speed
  initial_state: true
  hide_entity: false
  trigger:
  - platform: state
    entity_id: input_slider.porch_animation_speed
  action:
  - service: mqtt.publish
    data_template:
      topic: bruh/porch/set
      payload: '{"transition":{{ trigger.to_state.state | int }}}'
  id: 2b34a28c60154e6a9b1a717efc47b1dc
- id: '15410589874822'
  alias: tu Mở đèn Yeelight
  trigger:
  - entity_id: device_tracker.luong_note_8
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - data:
      entity_id: light.bed_room
    service: light.turn_on
    
- id: '1542965147978'
  alias: AUTO START DUCK DNS
  trigger:
    - event: start
      platform: homeassistant
  action:
     - wait_template: "{{ is_state('binary_sensor.ping_binary_sensor', 'on') }}"
     - service: hassio.addon_start
       data:
         addon: "core_duckdns"
