homeassistant:
  # Name of the location where Home Assistant is running
  name: NHÀ LÊ VĂN LƯỢNG
  # Location required to calculate the time the sun rises and sets
  latitude: 12.213596
  longitude: 109.183568 
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Ho_Chi_Minh
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages
# Show links to resources in log and frontend
#introduction:
emulated_hue: !include emulated_hue.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
input_number: !include input_number.yaml
input_boolean: !include input_boolean.yaml
switch: !include_dir_merge_list switches/
input_select: !include input_select.yaml
input_text: !include input_text.yaml
input_datetime: !include input_datetime.yaml
#darksky: b6c5d660a13581f2488e4e74c365aef3
#fpt: dfa6fba1b627431cb95533f1ab82308c
lovelace:
  mode: yaml
frontend:
  themes:
    happy:
      primary-color: pink
    sad:
      primary-color: blue
    sad 2:
      primary-color: red

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: uly9m5ktnmzov2y2
# Enables the frontend
notify:    
  - name: android
    platform: fcm-android
    server_key: MYSERVERKEY123456
  - name: android
    platform: fcm-android

  - platform: html5
    name: NOTIFIER_NAME
    gcm_api_key: AAAASyXwuv0:APA91bEymzPy7NKWHX_0tsTVthIvxEzEiMXjyS98Lbm7hBRJg6wgERsRSolyMSsqdoGuji4hj2LzT0KRZsXJ4ns1MCCw8cmVQFgtsz8vieRdX1Mu1FntFXpiHurpoK1rNv94lNjrGLL_
    gcm_sender_id: 322759080701
# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
http:
  api_password: 123456
  ssl_certificate: /home/homeassistant/dehydrated/certs/leluong76.duckdns.org/fullchain.pem
  ssl_key: /home/homeassistant/dehydrated/certs/leluong76.duckdns.org/privkey.pem
  base_url: leluong76.duckdns.org:8123
  
#   base_url: example.duckdns.org:8123
zone:
  - name: home
    latitude: 12.213596
    longitude: 109.183568
    icon: mdi:home
    passive: true
  - name: Work
    latitude: 12.207802
    longitude: 109.204697
    icon: mdi:work
  - name: office wife
    latitude: 12.220795
    longitude: 109.202557
    icon: mdi:work
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:
weather:
  - platform: darksky
    api_key: b6c5d660a13581f2488e4e74c365aef3
    forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
    monitored_conditions:
      - summary
      - minutely_summary
      - hourly_summary
      - daily_summary
      - nearest_storm_distance
      - nearest_storm_bearing
      - precip_type
      - precip_intensity
      - precip_probability
      - temperature
      - apparent_temperature
      - dew_point
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      - pressure
      - visibility
      - ozone
    update_interval:
      minutes: 30
# Sensors
sensor:
  # Weather prediction
  - platform: yr
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    # If errors occur, remove degree symbol below
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'
  - platform: mqtt
    name: "humi soy"
    state_topic: "humi/soy"
    unit_of_measurement: '%'
  - platform: darksky
    api_key: b6c5d660a13581f2488e4e74c365aef3
    monitored_conditions: 
      - summary
      - icon
      - nearest_storm_distance
      - apparent_temperature
      - temperature
      - humidity
      - pressure
      - uv_index
  - platform: template
    sensors:
      alarm:
        friendly_name: 'Timer1'
        value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.alarm_hour") | int, states("input_number.alarm_minute") | int) }}'
  - platform: template
    sensors:
      timer:
        friendly_name: "Thời gian đã chọn"
        value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.alarm_1_hour") | int, states("input_number.alarm_1_minutes") | int) }}'
  - platform: template    
    sensors:
      mattroi:
        friendly_name: "Mặt trời"    
        unit_of_measurement: 'Lặn'
        value_template: >-
          {% if is_state('sun.sun', 'above_horizon') %}
            Chưa
          {% elif is_state('sun.sun', 'below_horizon') %}
            Đã
          {% endif %}
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
  - platform: template
    sensors:
      weathertoday:
        friendly_name: "Thời tiết hôm nay" 
        value_template: >-
          {% if is_state('sensor.dark_sky_icon', 'partly-cloudy-day') %}
            Ngày trời ít mây
          {% elif is_state('sensor.dark_sky_icon', 'clear-day') %}
            Ngày trời trong xanh
          {% elif is_state('sensor.dark_sky_icon', 'clear-night') %}
            Đêm trời đẹp
          {% elif is_state('sensor.dark_sky_icon', 'rain') %}
            Trời mưa
          {% elif is_state('sensor.dark_sky_icon', 'wind') %}
            Gió nhiều
          {% elif is_state('sensor.dark_sky_icon', 'cloudy') %}
            Trời nhiều mây
          {% elif is_state('sensor.dark_sky_icon', 'partly-cloudy-night') %}
            Đêm trời nhiều mây
          {% elif is_state('sensor.dark_sky_icon', 'fog') %}
            Sương mù
          {% elif is_state('sensor.dark_sky_nearest_storm_distance', 'unknown') %}
            Không có cơn bão nào
          {% else %}
            ...
          {% endif %} 
  - platform: template
    sensors:
      battery_iphone:
        unit_of_measurement: '%'
        value_template: >
            {%- if states.device_tracker.iphone7.attributes.battery %}
                {{ states.device_tracker.iphone7.attributes.battery|round }}
            {% else %}
                {{ states.sensor.battery_iphone.state }}
            {%- endif %}
        icon_template: '{%- if is_state("sensor.battery_iphone", "unknown") %}mdi:battery-unknown{%- elif is_state_attr("device_tracker.iphone7", "battery_status", "Charging") %}mdi:battery-charging{%- elif  states.device_tracker.iphone7.attributes.battery <= 5 %}mdi:battery-outline{%- elif states.device_tracker.iphone7.attributes.battery >= 95 %}mdi:battery{% else %}mdi:battery-{{(states.device_tracker.iphone7.attributes.battery|float / 10)|round*10}}{%- endif %}'       
  - platform: mqtt
    state_topic: "owntracks/luong/note 8"
    name: "Battery Note 8"
    unit_of_measurement: "%"
    value_template: '{{ value_json.batt }}'
    device_class: battery        
  - platform: mqtt
    state_topic: "owntracks/luong/0C2A8368-36C3-4E00-AA03-1FE273BAC44D"
    name: "Battery Iphone 7"
    unit_of_measurement: "%"
    value_template: '{{ value_json.batt }}'
    device_class: battery
    
  - platform: template
    sensors:
      cambiennguoi_xiaomi:
        friendly_name: "Cảm biến người"
        value_template: >-
          {% if is_state('binary_sensor.motion_sensor_158d00027a31dd', 'on') %}
          Phát hiện có người trong phòng
          {% elif is_state('binary_sensor.motion_sensor_158d00027a31dd', 'off') %}
          Không có người trong phòng
          {% endif %}
  - platform: template
    sensors:
      cambien_mua:
        friendly_name: "Cảm biến mưa"
        value_template: >-
          {% if is_state('switch.cam_bien_mua', 'on') %}
          Trời đang mưa
          {% elif is_state('switch.cam_bien_mua', 'off') %}
          Trời không mưa
          {% endif %}        
  - platform: template
    sensors:
      cambiencua_xiaomi:
        friendly_name: "Cửa Cổng"
        value_template: >-
          {% if is_state('binary_sensor.door_window_sensor_158d0002b5b494', 'on') %}
          Mở
          {% elif is_state('binary_sensor.door_window_sensor_158d0002b5b494', 'off') %}
          Đóng
          {% endif %}
  - platform: template
    sensors:
      pin_cambiencua_xiaomi:
        friendly_name: "Pin cảm biến cửa cổng:"
        value_template: "{{ states.binary_sensor.door_window_sensor_158d0002b5b494.attributes.battery_level }}%"

  - platform: template
    sensors:
      pin_cambiencua_sanphoi:
        friendly_name: "Pin cảm biến cửa sân phơi:"
        value_template: "{{ states.binary_sensor.door_window_sensor_158d0002b5b57d.attributes.battery_level }}%"      
  - platform: template
    sensors:
      cambiennhietdo_xiaomi:
        friendly_name: "Nhiệt độ phòng ngủ"
        value_template: "{{states('sensor.temperature_158d000223fca2') }} °C"

  - platform: template
    sensors:
      cambienanhsang_xiaomi:
        friendly_name: "Cường độ sáng"
        value_template: "{{states('sensor.illumination_7c49ebb1b4c9') }} lm"

  - platform: template
    sensors:
      cambiendoam_xiaomi:
        friendly_name: "Độ ẩm phòng ngủ"
        value_template: "{{states('sensor.humidity_158d000223fca2') }} %"

  - platform: template
    sensors:
      pin_cambiennhietam_xiaomi:
        friendly_name: "Pin cảm biến ẩm:"
        value_template: "{{ states.sensor.humidity_158d000223fca2.attributes.battery_level }}%"
        
  - platform: mqtt
    name: "Công suất đang tải"
    state_topic: "tele/sonoff/SENSOR"
    value_template: "{{ value_json.ENERGY.Power }}"
    unit_of_measurement: "W"
    icon: mdi:power-plug
  
  - platform: mqtt
    name: "Công suất biểu kiến"
    state_topic: "tele/sonoff/SENSOR"
    value_template: "{{ value_json.ENERGY.ApparentPower }}"
    unit_of_measurement: "VA"
    icon: mdi:power-plug
    
  - platform: mqtt
    name: "Công suất phản kháng"
    state_topic: "tele/sonoff/SENSOR"
    value_template: "{{ value_json.ENERGY.ReactivePower }}"
    unit_of_measurement: "VAr"
    icon: mdi:power-plug

  - platform: mqtt
    name: "Điện áp"
    state_topic: "tele/sonoff/SENSOR"
    value_template: "{{ value_json.ENERGY.Voltage }}"
    unit_of_measurement: "V"
    icon: mdi:flash

  - platform: mqtt
    name: "Cường độ dòng điện"
    state_topic: "tele/sonoff/SENSOR"
    value_template: "{{ value_json.ENERGY.Current }}"
    unit_of_measurement: "A"
    icon: mdi:power-socket


  - platform: mqtt
    name: "Lượng điện tiêu thụ trong ngày"
    state_topic: "tele/sonoff/SENSOR"
    value_template: "{{ value_json.ENERGY.Today }}"
    unit_of_measurement: "kWh"
    icon: mdi:power-socket-eu

  - platform: mqtt
    name: "Lượng điện tiêu thụ hôm qua"
    state_topic: "tele/sonoff/SENSOR"
    value_template: "{{ value_json.ENERGY.Yesterday }}"
    unit_of_measurement: "kWh"
    icon: mdi:power-socket-eu
    
  - platform: mqtt
    name: "Lượng điện tiêu thụ tháng trước"
    state_topic: "tele/sonoff/SENSOR"
    value_template: "{{ value_json.ENERGY.Lastmonth }}"
    unit_of_measurement: "kWh"
    icon: mdi:power-socket-eu

  - platform: mqtt
    name: "Tổng lượng điện tiêu thụ"
    state_topic: "tele/sonoff/SENSOR"
    value_template: "{{ value_json.ENERGY.Total }}"
    unit_of_measurement: "kWh"
    icon: mdi:power-socket-eu

  - platform: mqtt
    name: "Hệ số công suất"
    state_topic: "tele/sonoff/SENSOR"
    value_template: "{{ value_json.ENERGY.Factor }}"
    icon: mdi:percent

  - platform: mqtt
    name: "Nhiệt độ phòng khách"
    state_topic: "tele/sonoff/SENSOR"
    value_template: "{{ value_json.DHT11.Temperature }}"
    unit_of_measurement: "°C"
    icon: mdi:thermometer
    
  - platform: mqtt
    name: "Độ ẩm phòng khách"
    state_topic: "tele/sonoff/SENSOR"
    value_template: "{{ value_json['DHT11'].Humidity }}"
    unit_of_measurement: "%"
    icon: mdi:water-percent
# Text to speech
tts:
  - platform: google
    language: vi
cover:
  - platform: mqtt
    name: "Giếng Trời Phải"
    command_topic: "dc1/cover/set"
    state_topic: "dc1/cover/state"
#    availability_topic: "home-assistant/cover/availability"
    qos: 0
    retain: true
    payload_open: "DIR"
    payload_close: "INV"
    payload_stop: "STOP"
    state_open: "dir"
    state_closed: "inv"
    # payload_available: "online"
    # payload_not_available: "offline"
    optimistic: false
  - platform: mqtt
    name: "Giếng Trời Trái"
    command_topic: "dc2/cover/set"
    state_topic: "dc2/cover/state"
#    availability_topic: "home-assistant/cover/availability"
    qos: 0
    retain: true
    payload_open: "DIR"
    payload_close: "INV"
    payload_stop: "STOP"
    state_open: "dir"
    state_closed: "inv"
    # payload_available: "online"
    # payload_not_available: "offline"
    optimistic: false
#    availability_topic: "home-assistant/cover/availability"
    # payload_available: "online"
    # payload_not_available: "offline"
   
  - platform: mqtt
    name: "RÈM NGOÀI"
    command_topic:  "door/cover/set"
    state_topic:    "door/cover/state"
 #   availability_topic: "door/cover/availability"
    qos: 0
    retain: true
    payload_open: "OPEN"
    payload_close: "CLOSE"
    payload_stop: "STOP"
    state_open: "open"
    state_closed: "closed"
    optimistic: false
  - platform: mqtt
    name: "RÈM TRONG"
    command_topic:  "door2/cover/set"
    state_topic:    "door2/cover/state"
 #   availability_topic: "door/cover/availability"
    qos: 0
    retain: true
    payload_open: "OPEN"
    payload_close: "CLOSE"
    payload_stop: "STOP"
    state_open: "open"
    state_closed: "closed"
    optimistic: false  
  - platform: template
    covers:
      garage_door:
        friendly_name: "Garage Door 1"
        value_template: "{{ states('sensor.garage_door')|float > 0 }}"
        open_cover:
          service: script.open_garage_door
        close_cover:
          service: script.close_garage_door
        stop_cover:
          service: script.stop_garage_door
  - platform: template
    covers:
      garage_door:
        friendly_name: "Garage Door 2"
        position_template: "{{ states('sensor.garage_door') }}"
        open_cover:
          service: switch.turn_on
          data:
            entity_id: switch.garage_door
        close_cover:
          service: switch.turn_off
          data:
            entity_id: switch.garage_door
        stop_cover:
          service: switch.turn_on
          data:
            entity_id: switch.garage_door
        icon_template: >-
          {% if states('sensor.garage_door')|float > 0 %}
            mdi:garage-open
          {% else %}
            mdi:garage
          {% endif %}
# Cloud
cloud:
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://leluong76.duckdns.org:3218

owntracks:
  max_gps_accuracy: 200
  waypoints: true
  mqtt_topic: "owntracks/#"
  events_only: true
  waypoint_whitelist:
    - jon
    - ram
  region_mapping:
    cabin: home
    office: work
media_player:
  - platform: alexa
    email: "leluongnt@gmail.com"
    password: "123456"
    url: "amazon.com"
  - platform: cast
    host: 192.168.1.7
  - platform: webostv
    host: 192.168.1.18
    name: Living Room TV
    filename: webostv.conf
    timeout: 5
    turn_on_action:
      service: persistent_notification.create
      data:
        message: "Turn on action"
    customize:
      sources:
        - livetv
        - youtube
        - makotv
        - netflix
binary_sensor:
  - platform: ping
    host: 8.8.8.8
    scan_interval: 20 
  - platform: ping
    host: 192.168.1.68
ifttt:
  key: cQBgnlPUuP4wUuBVjNTT1X
light:
  - platform: yeelight
    devices:
      192.168.1.19:
        name: Bed Room
        transition: 1000
        use_music_mode: True #(defaults to False)
        save_on_change: False
        #(defaults to True)

  - platform: flux_led 
    devices: 
      192.168.1.20: 
        name: led TV
# Example configuration.yaml
  - platform: flux_led
    devices:
      192.168.1.20:
        name: flux_lamppost
  - platform: mqtt
    name: "Porch Strip"
    schema: "json"
    state_topic: "bruh/porch"
    command_topic: "bruh/porch/set"
    effect: true
    effect_list:
      - bpm
      - candy cane  
      - confetti  
      - cyclon rainbow  
      - dots  
      - fire  
      - glitter  
      - juggle  
      - lightning
      - noise  
      - police all  
      - police one  
      - rainbow  
      - rainbow with glitter  
      - ripple  
      - sinelon  
      - solid  
      - twinkle  
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0
device_tracker:
  - platform: netgear
    host: 192.168.1.1
    username: admin
    password: 123456
    new_device_defaults:
      track_new_devices: true
      hide_if_away: false
  - platform: ping
    hosts:
      hostone: 192.168.1.168
  - platform: ping
    hosts:
      hostone: 192.168.1.15
  - platform: icloud
    username: leluongnt@gmail.com
    password: Luong123456
    account_name: iphone
    gps_accuracy_threshold: 500
  - platform: icloud2
    username: leluongnt@gmail.com
    password: Luong123456
    account_name: icloud_descriptive_name
    filter_devices: 'iphone7'
    gps_accuracy_threshold: 500
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: True
    
    events_only: True
climate:
  - platform: broadlink
    name: Máy lạnh Panasonic
    host: 192.168.1.2
    mac: 'b4:43:0d:38:a4:bd'
    ircodes_ini: 'broadlink_climate_codes/mitsubishi_electric.ini'
    min_temp: 16
    max_temp: 30
    target_temp: 27
    temp_sensor: sensor.temperature_158d000223fca2
    default_operation_from_idle: cool
    default_operation: cool
    default_fan_mode: mid
    customize:
      operations:
        - idle
        - cool
        
      fan_modes:
        - low
        - mid
        - high
google_assistant:
  project_id: 322759080701-af2pk0v8e44m7ujua1vddo4h104k82hr.apps.googleusercontent.com
  api_key: AIzaSyBhc3Y-Z71qcZezlVS7HHS_AXqfXasdZBo
  exposed_domains:
    - switch
    - light
    - group
    - cover
    - automation
    - input boolean
    - climate 
    - script 
    - fan
    - scene     
  entity_config:
    switch.kitchen:
      name: CUSTOM_NAME_FOR_GOOGLE_ASSISTANT
      aliases:
        - BRIGHT_LIGHTS
        - ENTRY_LIGHTS
    light.living_room:
      expose: false
      room: LIVING_ROOM
sonoff:
  username: '+84336328109'
  password: 12345678
  scan_interval: 60
  grace_period: 600
  api_region: 'as'
homekit:
  filter:
    include_domains:
      - alarm_control_panel
      - light
      - media_player
      - switch
      - fan
      - cover
      - input_boolean
      - script
      - climate
      - automation
  entity_config:
    alarm_control_panel.home:
      code: 1234
    light.kitchen_table:
      name: Kitchen Table Light
    lock.front_door:
      code: 1234
    media_player.phong_khach:
      feature_list:
        - feature: on_off
        - feature: play_pause
        - feature: play_stop
        - feature: toggle_mute
    switch.bedroom_outlet:
      type: outlet
weather_forecast:
media_extractor:
