resources:
  - url: /local/Custom_Cards/bignumber-card/bignumber-card.js
    type: js
  - url: /local/Custom_Cards/monster-card/monster-card.js
    type: js
  - url: /local/Custom_Cards/gauge-card.js
    type: js
  - url: /local/Custom_Cards/thermostat-card/thermostat-card.js
    type: module
  - url: /local/Custom_Cards/plan-coordinates/plan-coordinates.js
    type: js
  - url: /local/Custom_Cards/alarm_control_panel-card/alarm_control_panel-card.js
    type: js
  - url: /local/Custom_Cards/beer-card/beer-card.js
    type: js
  - url: /local/Custom_Cards/entity-attributes-card/entity-attributes-card.js
    type: js
  - url: /local/Custom_Cards/group-card/group-card.js
    type: js
  - url: /local/Custom_Cards/home-setter/home-setter.js
    type: js
  - url: /local/Custom_Cards/button-card/button-card.js
    type: module
  - url: https://unpkg.com/moment@2.23.0/moment.js
    type: js
  - url: /local/Custom_Cards/calendar-card/calendar-card.js
    type: module
  - url: /local/weatherbg-card.js
    type: module
  - url: /local/dark-sky-weather-card.js
    type: js
  - url: /local/custom-fan-card.js
    type: js
name: Orchard Cottages
views:
  - icon: mdi:home
    title: Home
    id: home
    background:
    theme:
    cards:
      - type: entities
        entities:
        - entity: media_player.google_home_mini
          name: Google Home
        #- entity: media_player.mibox3
        #  name: Mibox3
      - type: picture-glance
        title: Phòng Khách
        entities:
          - switch.ti_vi
          - switch.led_tv
          - light.porch_strip
          - input_number.porch_animation_speed
          - light.flux_lamppost
          - switch.original_xiaomi_mi_smart_wifi_socket
          - group.livingroom_fan
          - media_player.google_home_mini
          - entity: fan.living_room_fan
            icon: mdi:fan
        image: /local/pics/livingroom01.jpg
        tap_action:
          action: navigate
          navigation_path: /lovelace/1/

      - type: picture-glance
        title: Phòng Ngủ
        entities:
        - switch.quat_ngu_1
        - switch.quat_ngu_on_3
        - media_player.my_echo
        - light.yeelight_rgb_7c49eb1231a8
        - light.gateway_light_7c49ebb1b4c9
        - climate.bed_room_fan
        - climate.may_lanh_panasonic
        - cover.rem_trong
        - cover.rem_ngoai
        - fan.bedroom_fan
        state_image:
          "on": /local/pics/bedroom01.jpg
          "off": /local/pics/bedroom01off.jpg
        entity: light.yeelight_rgb_7c49eb1231a8
        tap_action:
          action: navigate
          navigation_path: /lovelace/2/
      - type: weather-forecast
        entity: weather.dark_sky
      - type: conditional
        conditions:
          - entity: light.led_tv
            state: "on"
        card:
          type: light
          entity: light.led_tv
  - icon: mdi:sofa
    title: Living Room
    id: living_room
    cards:
      - type: glance
        title: Phòng Khách
        background: no-repeat url("/local/livingroom01.jpg");
        show_header_toggle: true
        entities:
        - switch.tv
        - switch.original_xiaomi_mi_smart_wifi_socket
        - automation.mo_tv_30_phut
        - automation.mo_tv_60_phut
        - automation.tv_timer
        - group.livingroom_fan
        - media_player.google_home_mini
        - light.flux_lamppost
        - light.led_tv
        - light.porch_strip
        tap_action:
          action: toggle
      - type: picture
        image: https://images.pexels.com/photos/235975/pexels-photo-235975.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
        tap_action:
          action: navigate
          navigation_path: /lovelace/0/
  - icon: mdi:hotel
    title: Bedroom
    id: bedroom
    cards:
      - type: glance
        title: Phòng ngủ 1
        entities:
        - switch.quat_ngu_1
        - switch.quat_ngu_on_3
        - media_player.my_echo
        - light.yeelight_rgb_7c49eb1231a8
        - light.gateway_light_7c49ebb1b4c9
        - climate.bed_room_fan
        - automation.tu_mo_en_yeelight
        - climate.may_lanh_panasonic
        - cover.rem_ngoai
        - cover.rem_trong
        - fan.bedroom_fan
        - fan.turn_fan_off
        - media_player.my_echo
        tap_action:
          action: toggle
      - type: picture
        image: https://images.pexels.com/photos/235975/pexels-photo-235975.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
        tap_action:
          action: navigate
          navigation_path: /lovelace/0/