
title: NHÀ LÊ VĂN LƯỢNG
# Include external resources
resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/background.png") fixed
# Exclude entities from "Unused entities" view
excluded_entities:
  - weblink.router
views:
    # View tab title.
  - title: Example
    # Optional unique id for direct access /lovelace/${id}
    id: example
    # Optional background (overwrites the global background).
    background: radial-gradient(crimson, skyblue)
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    theme: dark-mode
    # The cards to show on this view.
    cards:
        # The filter card will filter entities for their state
      - type: entity-filter
        entities:
          - device_tracker.paulus
          - device_tracker.anne_there
        state_filter:
          - 'home'
        card:
          type: glance
          title: People that are home

        # The picture entity card will represent an entity with a picture
      - type: picture-entity
        image: https://www.home-assistant.io/images/default-social.png
        entity: light.bed_light

    # Specify a tab icon if you want the view tab to be an icon.
  - icon: mdi:home-assistant
    # Title of the view. Will be used as the tooltip for tab icon
    title: Second view
    cards:
        # Entities card will take a list of entities and show their state.
      - type: entities
        # Title of the entities card
        title: Example
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - light.kitchen
          - switch.ac
          - entity: light.living_room
            # Override the name to use
            name: LR Lights

        # The markdown card will render markdown text.
      - type: markdown
        title: Lovelace
        content: >
          Welcome to your **Lovelace UI**.



- type: vertical-stack
  cards:
    - type: media-control
      entity: media_player.tv
    - type: conditional
      conditions:
        - entity: media_player.tv
          state: "on"
      card:
        type: picture-elements
        image: /local/rect4.png
        elements:
          - type: icon
            tap_action: toggle
            entity: media_player.tv
            icon: mdi:power
            style:
              top: 7.5%
              left: 11%
              --iron-icon-height: 30px
              --iron-icon-width: 30px
          - type: icon
            tap_action: toggle
            entity: switch.mute
            icon: mdi:volume-mute
            style:
              top: 7.74%
              left: 28.5%
              color: '#a31a40'
              --iron-icon-height: 30px
              --iron-icon-width: 30px
          - type: icon
            tap_action: toggle
            entity: switch.input
            icon: mdi:video-input-hdmi
            style:
              top: 7.6%
              left: 45.4%
              color: '#a31a40'
              --iron-icon-height: 30px
              --iron-icon-width: 30px
          - type: icon
            tap_action: toggle
            entity: switch.setting
            icon: mdi:settings
            style:
              top: 7.5%
              left: 62.4%
              color: '#a31a40'
              --iron-icon-height: 30px
              --iron-icon-width: 30px
          - type: icon
            tap_action: toggle
            entity: switch.volume_up
            icon: mdi:plus
            style:
              top: 18.7%
              left: 11%
              color: '#a31a40'
              --iron-icon-height: 30px
              --iron-icon-width: 30px
          - type: icon
            tap_action: toggle
            entity: switch.volume_down
            icon: mdi:minus
            style:
              top: 38.6%
              left: 11%
              color: '#a31a40'
              --iron-icon-height: 30px
              --iron-icon-width: 30px
          - type: icon
            tap_action: toggle
            entity: switch.back
            icon: mdi:arrow-left-drop-circle
            style:
              top: 69.6%
              left: 11.6%
              color: '#a31a40'
              --iron-icon-height: 30px
              --iron-icon-width: 30px
          - type: icon
            tap_action: toggle
            entity: switch.up
            icon: mdi:circle
            style:
              top: 54%
              left: 50.3%
              color: '#a31a40'
              --iron-icon-height: 30px
              --iron-icon-width: 30px
          - type: icon
            tap_action: toggle
            entity: switch.left
            icon: mdi:circle
            style:
              top: 69.5%
              left: 28.8%
              color: '#a31a40'
              --iron-icon-height: 30px
              --iron-icon-width: 30px
          - type: icon
            tap_action: toggle
            entity: switch.right
            icon: mdi:circle
            style:
              top: 69.1%
              left: 72%
              color: '#a31a40'
              --iron-icon-height: 30px
              --iron-icon-width: 30px
          - type: icon
            tap_action: toggle
            entity: switch.down
            icon: mdi:circle
            style:
              top: 85.1%
              left: 50.25%
              --iron-icon-height: 30px
              --iron-icon-width: 30px
              color: '#a31a40'
          - type: icon
            tap_action: toggle
            entity: switch.ok
            icon: mdi:circle-slice-8
            style:
              top: 69.1%
              left: 50.25%
              color: '#a31a40'
              --iron-icon-height: 50px
              --iron-icon-width: 50px